language: go
go:
- tip
notifications:
  slack:
    secure: EcklmsJPCdTGcYGBWmVyJsqkzC9rf+7RUTymDaJ1nUMFyBCHFYQ8CdMzoJBCNXVSaKugc4krAvDXmc69pcRc0XXFhj6zWiu7QmvjGvuXYPq0+IrG+8P0uzGcdbzT9rSQpjIAlKiZBcWMzCO1PfPttL+dq4MHkFZUH6nvslzTSGrw6Lvlwe+CemrVb3U5NyzpZ2STz0fWuqJ8b5mNn4uTWTtFXEHzGq0+x91iLln1GhRWkRqNsN0O6ZhE65CJemEc9aPmEd7lZ/7ID4J+3umooORYF5rivAYIqCzv8YmkWfGK2YvO/PyGac2osqDGSmlVtwZK8dk1x7z9OVv8LWpV+y+geo0ZT+dHRJns7OkdPYMTZEPScgZ4isexCvSx8elSFNUTfN5aRF6EHn/nRjMq+0/NnAClHSVjDgU+CH/cX013ZEfeNOw0JlUomh6HKcAA14i7wPpJNueYc2oTh5heANYd1kj9LwbohR6ZsGm4/dHkq6WrfzkTurNBLaXFO/zJkzBY9Aw/JCMNqQkxxafyjhgcfxUDQpBgn6fAJ9aVgN9gaJ7JF6odbEVwzps8NKpz4H7mRZjjI/KrxBzASbKGFzud+QtRmYofQ3yUMwSK2tVgmfx9pbHUxAw6V0RqL6AyM79V+kVtOCc1MCcZFJG8AFeGtfK6SM/g1gZI06xUOBA=
