baseurl = "http://otter.vektor.nyc/docs"
title = "Otter"
languageCode = "en-us"
MetaDataFormat = "toml"
theme = "hugo-theme-bootie-docs"
paginate = 10

[author]
    name = "VektorLab"
[params]
  github = "vektorlab/otter"
  email = "contact@vektor.nyc"
  mainMenu = ["Getting Started"]
  logo = "/img/otter.png"
  noCategoryLink = true
  description = "Otter is an opinionated container-oriented configuration management framework written in Go."
